#pragma once

enum class ProjectileType {
    // bullet
    ARROW,
    BAD_PISTOL_BULLET,
    RED_DIAMOND_BULLET,
    RED_RECTANGLE_BULLET,
    RED_CIRCLE_BULLET,
    RED_SPLINTER_BULLET,
    GAS_BLASTER_BULLET,
    RED_SQUARE_BULLET,
    BIG_RED_CIRCLE_BULLET,
    RED_HOLLOW_CIRCLE_BULLET,
    RED_CONICAL_BULLET,
    SPIRAL_BULLET,
    ZULAN_ANGRY_BULLET,

    // shock wave
    HAMMER_WAVE,
    BLOW_UP,

    // other
    INVISIBLE_SHOCK_WAVE,

    // count
    COUNT
};
