#pragma once

enum class MonsterType {
    // floor 1
    DEVELS_SNARE,

    GOBLIN_GUARD_SPEAR,
    GOBLIN_GUARD_PISTOL,
    GOBLIN_GUARD_BOW,

    ELITE_GOBLIN_GUARD_SHOTGUN,
    ELITE_GOBLIN_GUARD_DART,
    ELITE_GOBLIN_GUARD_HOE,

    GOBLIN_SHAMAN,
    GOBLIN_GIANT,

    // TRUMPET_FLOWER,

    NORMAL_BOAR,
    DIRE_BOAR,

    // floor 2
    // C6H8O6,

    SKELETON_BOW,
    SKELETON_CURVED_SWORD,
    SKELETON_SHOTGUN,

    ELITE_SKELETON_CURVED_SWORD,
    ELITE_SKELETON_RIFLE,
    ELITE_SKELETON_SHOTGUN,
    
    SKELETON_SHAMAN,
    BIG_SKELETON,

    SPIDER,
    POISON_SPIDER,
    BATTERY,

    // floor 3
    ZULAN,

    ALIEN_MACHINE_GUN,
    ALIEN_RED_LIGHTSABER,
    UFO,

    // GOBLIN,
    // GOBLIN_FLY,

    VARKOLYN_GUARD_AXE,
    VARKOLYN_GUARD_MACHINE_GUN,
    // VARKOLYN,

    COUNT
};
